const actionType = {
	LOGIN: "LOGIN",
	ADD_PRODUCT: "ADD_PRODUCT",
	EDIT_PRODUCT: "EDIT_PRODUCT",
	DELETE_PRODUCT: "DELETE_PRODUCT",
	APPROVE_CLAIMS: "APPROVE_CLAIMS",
	REJECT_CLAIMS: "REJECT_CLAIMS",
	REVERT_CLAIMS: "REVERT_CLAIMS",
};

export default actionType;
